### PR TITLE
Use skin cells for BC in femparproj src stencil

### PR DESCRIPTION
**Pull request by akashukla**
Unit test in g0 passes continuity and BC checks

### CODE REVIEW

**Comment by manauref** [comment]
@akashukla can I see the corresponding commit in gkylzero?

**Comment by akashukla** [comment]
this is the corresponding g0 commit. https://github.com/ammarhakim/gkylzero/commit/070a78414a8df6eaaa4842bb7d4687a67e04bccb

**Comment by manauref** [comment]
I'm gonna wait to merge this until we merge gk-g0-app, otherwise the maxima will be inconsistent with what's in gkylzero main

**Comment by manauref** [comment]
@akashukla actually you could merge this into gkylcas' gk-g0-app branch

**Pull request closed without merging**
